# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SerializeJSON' do

  use_frameworks!
  
  pod 'Alamofire', '~> 4.7'
  pod 'AlamofireImage', '~> 3.3'

end